### ISSUE TITLE
Supabase result is misleading (data returned is null from db)

### ISSUE THREAD

**Issue by GorvGoyl** [vercel-labs/function-database-latency#33]
When testing from Asia (Thailand) Supabase gave 100ms latency for global edge function and it seems too good to be true (afaik supabase db is in the US). Upon debugging, I discovered the data returned from the DB is null. I inspected it from the browser console log.

![image](https://github.com/vercel-labs/edge-data-latency/assets/7106086/5e92ae41-6272-4826-ab4d-1ab6183a46af)

![screenshot 2023-12-09 at 14 35 52@2x](https://github.com/vercel-labs/edge-data-latency/assets/7106086/20acafd3-6862-44b0-828c-4c02e92335b9)

I compared it with another Postgres provider, neon tech, and it gave 3.5sec latency and the data was returned.

![screenshot 2023-12-09 at 14 39 31@2x](https://github.com/vercel-labs/edge-data-latency/assets/7106086/b043456f-d1c4-4625-97dc-d5d7fc9852f6)

**Comment by leerob** [comment]
This should now be resolved! Thank youl
